SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE emp (
  id int(11) NOT NULL,
  name varchar(50) DEFAULT NULL,
  address varchar(50) DEFAULT NULL,
  salary double DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO emp (id, name, address, salary) VALUES
(1, 'Priyanka', 'Thane', 30000),
(3, 'Swara', 'Bhiwandi', 32000),
(4, 'poonamp', 'thane', 320000);


ALTER TABLE emp
  ADD PRIMARY KEY (id);


ALTER TABLE emp
  MODIFY id int(11) NOT NULL AUTO_INCREMENT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
